name: Deploy to Google App Engine

on:
  push:
    tags:
      - 'v*'  # Déclenchement uniquement sur les tags de version

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Download model with gcloud storage
      run: |
        gcloud storage cp gs://kadi_model_ticket/model_complet.pth src/crop_ticket/model_complet.pth

    - name: Verify model file
      run: |
        test -f src/crop_ticket/model_complet.pth || { echo "Model file is missing!"; exit 1; }

    - name: Check model file size
      run: |
        if [[ $(stat --printf="%s" src/crop_ticket/model_complet.pth) -lt 100000 ]]; then
          echo "Model file seems too small! Check the source or permissions.";
          exit 1;
        fi

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: c-troop-70f68
        install_components: app-engine-python

    - name: Deploy to App Engine
      run: |
        gcloud app deploy \
          --no-promote \
          --quiet \
          --project=c-troop-70f68
      env:
        CLOUDSDK_COMPUTE_MACHINE_TYPE: "n1-highcpu-4" # Machine plus puissante