name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # Déclenche le déploiement uniquement sur la branche main
  pull_request:
    branches:
      - main  # Optionnel, pour tester aussi lors des pull requests sur main

jobs:
  deploy:
    name: Deploy to App Engine
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Mise à jour vers la dernière version v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1  # Utilisation de l'action d'authentification
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: c-troop-70f68  # Remplace par l'ID de ton projet GCP
        install_components: app-engine-python

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet