        name: Deploy to Google App Engine

        on:
          push:
            tags:
              - 'v*'  # Déclenchement uniquement sur les tags de version
        
        jobs:
          deploy:
            name: Deploy to Production
            runs-on: ubuntu-latest
            steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Authenticate to Google Cloud
              uses: google-github-actions/auth@v1
              with:
                credentials_json: ${{ secrets.GCP_SA_KEY }}

            - name: Restore model file
              run: |
                curl -o src/crop_ticket/model_v1.pth "https://storage.googleapis.com/kadi_model_ticket/model_v1.pth"
        
            - name: Set up Cloud SDK
              uses: google-github-actions/setup-gcloud@v1
              with:
                project_id: c-troop-70f68
                install_components: app-engine-python
        
            - name: Deploy to App Engine
              run: |
                gcloud app deploy \
                  --no-promote \
                  --quiet \
                  --project=c-troop-70f68
              env:
                CLOUDSDK_COMPUTE_MACHINE_TYPE: "n1-highcpu-4" # Machine plus puissante